### ISSUE TITLE
the blueberry sandwich crash

### ISSUE THREAD

**Issue by A-Fella** [purejosh/sweetberryfoods#11] opened 2024-01-09 17:37 UTC
**Describe the bug**
I don't know if it's a mod conflict or something, but 

every time I craft a blueberry sandwich my game crashes.

**To Reproduce**
for me, it's just, making a sandwich lmao

<img width="208" alt="Screenshot 2024-01-09 at 12 31 33 PM" src="https://github.com/purejosh/pureberries/assets/156117865/57793a4c-21f1-4cf4-9178-c3d5e8b0ab15">
<img width="300" alt="Screenshot 2024-01-09 at 12 30 49 PM" src="https://github.com/purejosh/pureberries/assets/156117865/f5369899-6ec2-4097-845e-2920e1835996">

I'm a CurseForge user and it's fully updated. screenshots list all the mods I'm using, and the version info. I am new to GitHub so I have no idea what this si gonna look like once I submit OR WHAT IMAGES ARE WHERE! lmaooooo
<img width="293" alt="Screenshot 2024-01-09 at 12 30 59 PM" src="https://github.com/purejosh/pureberries/assets/156117865/d1cac7d8-3ffc-4762-8e15-5c695499cfca">

edit: figured a crash report could be helpful???? i have no idea how to read them or if its even like, viable??? but, here haha

[crash-2024-01-09_12.17.13-client.txt](https://github.com/purejosh/pureberries/files/13877182/crash-2024-01-09_12.17.13-client.txt)
[crash-2024-01-09_12.22.52-client.txt](https://github.com/purejosh/pureberries/files/13877186/crash-2024-01-09_12.22.52-client.txt)

**Comment by purejosh** [comment] 2024-01-09 20:41
That's incredibly unusual, because there's nothing special about the blueberry jam sandwich. I will download quilt, and test with just Pure Berries.

**Comment by purejosh** [comment] 2024-01-09 21:08
I *can* recreate this. I'll talk to the quilt team to see why this works on Fabric, but not on quilt.

**Comment by purejosh** [comment] 2024-01-09 21:16
This is being caused by the Jam bottles. When they are used, they are replaced in the crafting grid with a bottle. This works on Fabric, Forge, and Vanilla. I may release a fixed version where the jam is not replaced with a bottle, just to resolve this issue, unless the Quilt devs can find it immediately.

**Comment by purejosh** [comment] 2024-01-16 01:44
This has been resolved in the latest release, v4.0.2.

**Closed as completed by purejosh** 2024-01-16 01:44 UTC
Labels: bug
